Repository icosa-foundation/open-blocks, pull requests merged in 2024-09, with the labels that each got.

#34 New Modify Tool mode based on previously experimental "plane subdivide"
  Assets/Mogwai/Design/Icons/ic_modify_subdivide_plane.png
  Assets/Mogwai/Design/Icons/ic_modify_subdivide_plane.png.meta
  Assets/Prefabs/ControllerGeometryLeftRift.prefab
  Assets/Prefabs/ControllerGeometryRightRift.prefab
  Assets/Scripts/model/controller/ChangeModeMenuItem.cs
  Assets/Scripts/model/controller/ControllerMode.cs
  Assets/Scripts/model/controller/PaletteController.cs
  Assets/Scripts/model/controller/PeltzerController.cs
  Assets/Scripts/model/main/Features.cs
  Assets/Scripts/model/main/PeltzerMain.cs
  Assets/Scripts/tools/Subdivider.cs
Labels: enhancement

#48 Use the original algorithm when extruding a single face
  Assets/Scripts/tools/Extruder.cs
  Assets/Scripts/tools/ExtrusionOperation.cs
Labels: bugfix

#49 gzip config.vdf before storing as a secret
  .github/workflows/build.yml
Labels: infrastructure

#50 Run the build on 'main' periodically to keep the caches alive
  .github/workflows/build.yml
Labels: infrastructure
